export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const ADD_GAME_START = "ADD_GAME_START";
export const ADD_GAME_SUCCESS = "ADD_GAME_SUCCESS";
export const ADD_GAME_FAIL = "ADD_GAME_FAIL";

export const DELETE_GAME_START = "DELETE_GAME_START";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAIL = "DELETE_GAME_FAIL";

export const SORT_BY_USER = "SORT_BY_USER";
export const SORT_BY_LEGEND = "SORT_BY_LEGEND";
export const SORT_BY_RANK = "SORT_BY_RANK";
export const SORT_BY_KILLS = "SORT_BY_KILLS";
export const SORT_BY_DAMAGE = "SORT_BY_DAMAGE";
export const SORT_BY_REVIVES = "SORT_BY_REVIVES";
export const SORT_BY_RESPANWS = "SORT_BY_RESPANWS";
export const SORT_BY_PLATFORM = "SORT_BY_PLATFORM";
export const SORT_BY_DATE = "SORT_BY_DATE";
